
const axios = require('axios');
const token= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImRhdGVfY3JlYXRpb24iOjE2MTg1OTEzNzI3OTcsImRhdGVfdXBkYXRlIjoxNjE4NTkxMzczNDI4LCJpZCI6MywidXNlcm5hbWUiOiJjbGFyYSIsInBob25lTnVtYmVyIjoiKzIzNzY5NTg2NzE0NCIsInJlZmVyYWxDb2RlIjoiVXNTS2ttNGk2aTVhNnBOIiwibGFzdFNlZW5BdCI6MTYxODU5MTM3Mjc5NiwidG9zQWNjZXB0ZWRCeUlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInBob25lSWQiOiIzNjY0IiwiY3VzdG9tZXJUeXBlIjp7ImRhdGVfY3JlYXRpb24iOjE2MTY3NjM2NDIyNDIsImRhdGVfdXBkYXRlIjoxNjE2NzYzNjQyMjQyLCJpZCI6MSwiZGVzY3JpcHRpb24iOiJjbGllbnQiLCJpc0RlZmF1bHQiOnRydWV9LCJjb3VudHJ5Ijp7ImRhdGVfY3JlYXRpb24iOjE2MTY3NjM1MzM4NjQsImRhdGVfdXBkYXRlIjoxNjE4NTg4NjA1OTc3LCJpZCI6NDEsInNob3J0Q291bnRyeUNvZGUiOiJDTSIsImNvdW50cnlDb2RlIjoiQ01SIiwiY291bnRyeVByZWZpeCI6IjIzNyIsImNvdW50cnlOYW1lRW4iOiJDYW1lcm9vbiIsImNvdW50cnlOYW1lRnIiOiJDYW1lcm91biIsImNhblNlbGwiOnRydWUsImNhbkJ1eSI6dHJ1ZSwiY2FuRGVwb3NpdCI6dHJ1ZSwiY2FuV2l0aGRyYXciOnRydWUsImNhblNlbmQiOnRydWUsImNhbkV4Y2hhbmdlIjp0cnVlLCJwcmltYXJ5Q3VycmVuY3kiOjM1LCJzdGF0dXMiOm51bGwsImFjdGl2ZVBheW1lbnRQcm92aWRlciI6MX0sInN0YXR1cyI6eyJkYXRlX2NyZWF0aW9uIjoxNjE2NzYzNjQyNjU2LCJkYXRlX3VwZGF0ZSI6MTYxNjc2MzY0MjY1NiwiaWQiOjEsImRlc2NyaXB0aW9uIjoiY3JlYXRlZCIsImFjY291bnRJc09wZW4iOnRydWUsImlzRGVmYXVsdCI6dHJ1ZX0sImxhYmVsIjoxLCJkZXRhaWxzIjp7ImRhdGVfY3JlYXRpb24iOjE2MTg1OTEzNzMyMTksImRhdGVfdXBkYXRlIjoxNjE4NTkxMzczMjE5LCJpZCI6MywiZmlyc3ROYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJnZW5kZXIiOiIiLCJlbWFpbEFkZHJlc3MiOiJrY2xhdWRlam9lbDIwQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOm51bGwsInByZWZlcnJlZExhbmd1YWdlIjoiZnIiLCJpbkFwcE5vdGlmaWNhdGlvbnMiOnRydWUsImFwcFNjcmVlbnNob3RzIjpmYWxzZSwibW9vbnBheUN1c3RvbWVySWQiOm51bGwsImN1c3RvbWVyIjozLCJwcmVmZXJyZWRGaWF0Q3VycmVuY3kiOjM1fSwicmVmZXJyZXIiOm51bGwsIm1hbmFnZXIiOm51bGwsImxveWFsdHlMZXZlbCI6bnVsbH0sImlhdCI6MTYxODU5MTM3NSwiZXhwIjoxNjE4Njc3Nzc1LCJhdWQiOiJlamFyYS5pbyIsImlzcyI6ImVqYXJhLmlvIn0.9z0eZ6z9II3lduNMuu0XsVnLDquUbRuMvW1esi4nEkc';
axios.get('https://sandbox.nellys-coin.ejaraapis.xyz/api/v1/customer/profile-details',
  {
    headers: {
      'Authorization': `Bearer ${token}`
    }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
    // always executed
  });  

